on: [push, pull_request]
name: Static analysis
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:php8.0
        with:
            args: php-cs-fixer fix --dry-run -vvv

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://jakzal/phpqa:php8.0
        with:
          args: phpstan analyze --no-progress
